### ISSUE TITLE
Example .h file missing!

### ISSUE THREAD

**Issue by gjt211** [ThisSmartHouse/CoogleIOT#1]
I have downloaded and installed your library, but am unable to compile your example as the GarageDoor-Opener.h file is missing. I am unable to find it on GitHub.
Can you please provide the file?

**Comment by KBoonie** [comment]
September 6th and it's still missing.  The lack of a functioning example does make one wonder.

**Comment by coogle** [comment]
Sorry! I will commit that file now!

**Comment by coogle** [comment]
Added to master - and I will do a release as well.
