### ISSUE TITLE
Basic CoogleIoT example crashes device?

### ISSUE THREAD

**Issue by fontanon** [ThisSmartHouse/CoogleIOT#10]
Hi. 

I don't know whether CoogleIoT does something weird, or it is me who doesn't really understand how to use it or setup properly.

I've downloaded CoogleIoT v1.3.1 (github) and flashed the following sample firmware to a LoLin NodeMCU v3 dev board. After flashing it, the device does not stops flashing the main led. No wifi hotspot is published, and a lot of garbage is printed in the Serial Monitor of the Arduino studio. 

```c
#include <ESP8266WiFi.h>
#include <CoogleIOT.h>

const int SERIAL_BAUD = 115200;
const int SleepTime = 5e6;

CoogleIOT *iot;

void setup() {
  iot = new CoogleIOT(LED_BUILTIN);

  iot->enableSerial(SERIAL_BAUD)
    .initialize();

  iot->info("Setup finalised");
}

void loop() {
  iot->loop();
  iot->info("Going to sleep");
  ESP.deepSleep(SleepTime); // Going to sleep. Pins are circuited correctly.
}
```

Any clue? Thanks in advance.

**Comment by coogle** [comment]
Can you provide what you do see on the Serial Port? You shouldn't need to include ESP8266WiFi.h (it is already included in CoogleIOT.h), but  offhand your code looks correct to me.

**Comment by coogle** [comment]
Closing since never heard back.
