### ISSUE TITLE
WifiClientPrint.h - wrong file name

### ISSUE THREAD

**Issue by sweetagar** [ThisSmartHouse/CoogleIOT#2]
Error during compiling: CoogleIOT/src/CoogleIOTWebserver.h:29:29: fatal error: WifiClientPrint.h: No such file or directory
 #include "WifiClientPrint.h"

Apparently the src file name is wrong "WiFiClientPrint.h" (capital "F")

Change the filename back to "WifiClientPrint.h" would solve the issue.

**Comment by coogle** [comment]
Opps! Looks like I didn't catch this because in my env (Mac OS X) WifiClientPrint.h and WiFiClientPrint.h are the same file (it's case insensitive -- very annoying). Fixed the proper case and it should be available for 1.2.2
